# Generated by Django 4.2 on 2023-04-30 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=200)),
                ('degree', models.CharField(choices=[('硕士', '硕士'), ('博士', '博士')], help_text='学位', max_length=32)),
                ('grade', models.CharField(choices=[('一年级', '一年级'), ('二年级', '二年级'), ('三年级', '三年级')], help_text='年级', max_length=32)),
                ('training_type', models.CharField(choices=[('学术型', '学术型'), ('专业型', '专业型')], help_text='培养类别', max_length=32)),
                ('research_direction', models.TextField(help_text='研究方向')),
                ('graduated_date', models.DateField(help_text='毕业时间')),
                ('department', models.ForeignKey(help_text='本月所在科室', on_delete=django.db.models.deletion.CASCADE, to='researches.department')),
                ('supervisor', models.ForeignKey(help_text='导师', on_delete=django.db.models.deletion.CASCADE, to='researches.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('已发表文章', '已发表文章'), ('注册临床试验', '注册临床试验'), ('正在写的文章', '正在写的文章')], help_text='成果类型', max_length=32)),
                ('title', models.CharField(help_text='标题', max_length=200)),
                ('progress', models.CharField(help_text='进度', max_length=200)),
                ('student', models.ForeignKey(help_text='学生', on_delete=django.db.models.deletion.CASCADE, to='researches.student')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('临床研究', '临床研究'), ('临床转化', '临床转化'), ('基础研究', '基础研究')], help_text='研究性质', max_length=32)),
                ('content', models.TextField(help_text='研究内容')),
                ('plan', models.TextField(help_text='研究计划')),
                ('student', models.ForeignKey(help_text='学生', on_delete=django.db.models.deletion.CASCADE, to='researches.student')),
            ],
        ),
    ]
